### ISSUE TITLE
capture ecran gpo

### ISSUE THREAD

**Issue by jeromedaniel01** [WildCodeSchool/TSSR-2405-P3-G3-BuildYourInfra-Ekoloclast#4]
![Capture d'écran 2024-07-22 204426](https://github.com/user-attachments/assets/3afbd962-3074-4fd9-b183-fed5302d8179)
![Capture d'écran 2024-07-22 211745](https://github.com/user-attachments/assets/894f75e3-d2e2-4807-b8c1-558f5297cfb3)
![Capture d'écran 2024-07-22 205647](https://github.com/user-attachments/assets/0ded9db4-27d6-41cd-ab0e-c2c879423d42)
![Capture d'écran 2024-07-22 210756](https://github.com/user-attachments/assets/8ef140be-2247-4466-a09a-ff395768f0d1)
![Capture d'écran 2024-07-22 211745](https://github.com/user-attachments/assets/a0e249ec-a081-4c5c-8a46-fdc83eddd21a)
![Capture d'écran 2024-07-22 212005](https://github.com/user-attachments/assets/c30402b0-fd7a-4b59-8bc5-0f3c9cbc485c)
![Capture d'écran 2024-07-22 212203](https://github.com/user-attachments/assets/f4be9528-c221-4acf-b5be-0ba7d6cef3a1)

**Comment by damdupre** [comment]
top
