### ISSUE TITLE
capture ecran creation OU

### ISSUE THREAD

**Issue by jeromedaniel01** [WildCodeSchool/TSSR-2405-P3-G3-BuildYourInfra-Ekoloclast#5]
![script import CSV](https://github.com/user-attachments/assets/4a3e77bf-f8e8-4164-99e2-58abefd23120)
![Import fichier CSV](https://github.com/user-attachments/assets/70300232-7fae-4424-a4c4-101681232e2c)
![normalisation](https://github.com/user-attachments/assets/9524ce89-a97c-4456-8d3d-184cf5b7340e)
![import](https://github.com/user-attachments/assets/8e95817e-1cd7-41ca-983b-bcff12fe1401)
![creation OU et sousOU](https://github.com/user-attachments/assets/b77aee82-9160-487d-a7ab-9dd306b64395)
![Ajout utilisateur et MAJ](https://github.com/user-attachments/assets/843de1b7-02ea-440e-a59a-dca9186e69f2)
![activation et mdp](https://github.com/user-attachments/assets/fcd14730-13e6-4928-a81c-7961b09a3e73)
![creation et maj utilisateurs](https://github.com/user-attachments/assets/7098c3f3-b0c4-4f62-8f95-ac4c3aad8d3e)
![changement mdp](https://github.com/user-attachments/assets/1c36db7b-5141-48e6-b315-e86ef9e1be86)
![OU créés](https://github.com/user-attachments/assets/3bfd4495-e3e4-4e11-a1dc-7e23cd4287bc)

**Comment by damdupre** [comment]
top
